### ISSUE TITLE
Shop Pages have Alumni without images

### ISSUE THREAD

**Issue by Imtraped** [worcestertechnicalhighschool/techhigh.us#435]
5 Shop pages have Alumni spotlights but there is no image of that person.

These are the Shops:
Electrical
Culinary Arts
Graphic Communication
Allied Health
Cosmetology

ISS&N has the images, but they throw a 401 error on load. (Network in Inspect Element.)

**Comment by Imtraped** [comment]
401 is the Unauthorized Error.

**Comment by GabePng** [comment]
Done - All the alumni pictures are back in place expect for Allied Health.
