### ISSUE TITLE
Coach Contact Information section on Athletics is shown incorrectly

### ISSUE THREAD

**Issue by WaffleLord360** [worcestertechnicalhighschool/techhigh.us#581]
On the Athletics page of the most recent version of the code, the listed coaches and faculty are ordered in a vertical, single-card format, rather than the standard. The text about the season is centered, however. Provided is a snippet of what it looks like currently:

![Screenshot 2023-12-01 at 13-02-04 Athletics](https://github.com/worcestertechnicalhighschool/techhigh.us/assets/90159803/b310c93d-2048-491c-994e-a7b7e8eb2d50)

**Comment by Imtraped** [comment]
The issue was caused by a col-3 class, however the page **didn't** need it. As when I removed it, the page went back to normal. However, there is now a gap in between two images in the winter sports section, there will be a new issue for that.
