### ISSUE TITLE
Bullet points and Indentation on dev branch look off in multiple places

### ISSUE THREAD

**Issue by WaffleLord360** [worcestertechnicalhighschool/techhigh.us#582]
Throughout the website, several places where there are indents and bullet points look... quite off compared to the current version of the website. Below is an image of the General Advisory Board, where the bullet points are going farther left than the text above it.
![Screenshot 2023-12-01 at 13-11-05 General Advisory Board](https://github.com/worcestertechnicalhighschool/techhigh.us/assets/90159803/3cf98be9-b5bb-446c-868d-d6e35749c28b)

There are most likely more places where this occurs.

**Comment by Imtraped** [comment]
Fixed the markdown; all set.
