### ISSUE TITLE
Unusual space.

### ISSUE THREAD

**Issue by Imtraped** [worcestertechnicalhighschool/techhigh.us#583]
In the developer web tools, I was looking at one of the pages in the mobile emulation device, and I noticed that there was a big space between two words.

<img width="382" alt="image" src="https://github.com/worcestertechnicalhighschool/techhigh.us/assets/91901629/7758e6bf-a7af-47f8-8d5d-654d5f35bde6">

I also checked the website on my phone and the issue is there too.
![image](https://github.com/worcestertechnicalhighschool/techhigh.us/assets/91901629/675f3eeb-070d-46a8-9589-f23af66fb7d0)

**Comment by WaffleLord360** [comment]
For context (and to possibly fix the wording of this), this space shows up on the bottom of pages, where the WPS footer is, and is only seen when viewn on mobile, or when looking at the inspect-element version of mobile. 
This space is also visible on other portions of the footer.
![another-space](https://github.com/worcestertechnicalhighschool/techhigh.us/assets/90159803/4d4b51e5-e7c5-4c52-b089-143b46c9b85c)

**Comment by WaffleLord360** [comment]
The space issue has been fixed, the problem was that the way the text was aligned was Justify. Im not sure how this made the strange spaces, but all it took was changing it to Center.
