### ISSUE TITLE
Pages that need to get fixed on mobile

### ISSUE THREAD

**Issue by mohammedarts** [worcestertechnicalhighschool/techhigh.us#586]
There are a variety of pages that look on mobile, if any others are found reply with it and I'll add it to this issue. Also reply saying that you've fixed certain pages if that's been done.

PAGES:
~~-Academy pages (maybe? It still has the sub headers when nothing else does so we'll have to talk to finance.)~~
~~-Athletics (calendar)~~
~~-Credit Union(page doesn't fit on screen,  also finance said that the credit union is gone so we should just comment this page out.)~~
~~-Graphics Print Shop(page doesn't fit on screen. (prob due to images)~~
~~-Salon (page doesn't fit on screen. (prob due to images)~~
~~-Skyline Bistro (page doesn't fit on screen. (prob due to images)~~
~~-Tufts at Tech (page doesn't fit on screen. (prob due to images)~~
~~-Admissions~~
~~-Events~~
~~-Meet Principal (page doesnt fit on screen, the design of the page itself is ugly and outdated.)~~

**Comment by Imtraped** [comment]
Athletics, Graphics Print Shop, Tufts at Tech, Admissions, Events fixed. Also the contributors page was broken as well, but I fixed it as well.
