### ISSUE TITLE
Difference in Calenders

### ISSUE THREAD

**Issue by Imtraped** [worcestertechnicalhighschool/techhigh.us#588]
After I fixed the calendars on the events page and the athletics page, I noticed that they're different sizes, on mobile when, ideally they should have the same size.

**Comment by mohammedarts** [comment]
This has been fixed and now they're the same size. The issue is that we set an aspect ratio and content height for the athletics calendar, but not the event one, so I set the events calendar to have the same aspect ratio and content height.
