### ISSUE TITLE
Student Job Board's Button

### ISSUE THREAD

**Issue by Imtraped** [worcestertechnicalhighschool/techhigh.us#597]
The button's background is too dark to see the text that's on it, I have no problem with the hover classes.

This is what it looks like now:
![image](https://github.com/worcestertechnicalhighschool/techhigh.us/assets/91901629/37a6484b-55d2-4289-9a65-63911601dce2)

This is a accessibility issue (According to Firefox).

**Comment by mohammedarts** [comment]
Fixed, it was a problem where $primary and $white were switched.
