### ISSUE TITLE
The Academy Pages

### ISSUE THREAD

**Issue by Imtraped** [worcestertechnicalhighschool/techhigh.us#601]
The background images done on the pages are not CSS, even though they should be. _For Seniors, they picked some odd design choices._ What I'm thinking is that we make them background images or turn some of the markdown into HTML. IMO, we should have used HTML from the start of this thing, a lot of issues would have been prevented.

**Comment by EduardoWebDevelopment** [comment]
This issue will be closed for now, but if the new code in the dev branch does nothing (which wouldn't be surprising), then it can be opened again.
