### ISSUE TITLE
Have finance add Bowling to the list of sports on their end

### ISSUE THREAD

**Issue by Jek9000** [worcestertechnicalhighschool/techhigh.us#78]

**Comment by jeffhow** [comment]
Good catch. This is a technicality. A club has less organization and restrictions. Skateboarding and e-sports are technically a club (rolling participation, volunteer advisor, basic admin oversight), but bowling is definitely a sport and falls under the hierarchy of athletics  (application/tryouts membership, regulated play, stipend coaches, WPS athletics oversight). Ski/snowboarding my be a hybrid. 

Let's check in with F&M. This is their decision to research and make the call it should go on their Trello board.

**Comment by Jek9000** [comment]
Bowling is the only thing in this list thats actually a sport. Skateboarding and Skiing are clubs and will be added and labeled as such. I asked Ms. Paulino and she said they don't do tryouts or anything like that while bowling does. I'll still double check though
